"use client";

import { FileUp, FileText, LockKeyhole, ShieldCheck } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { AppShell } from "../components/app-shell";

const API = process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8080/api";

export default function UploadPage() {
  const [token, setToken] = useState(""); const [admin, setAdmin] = useState(false); const [file, setFile] = useState<File>(); const [status, setStatus] = useState("");
  const [form, setForm] = useState({ title: "", classification: "internal", departments: "operations", roles: "requester" });
  useEffect(() => { setToken(localStorage.getItem("procurement_token") || ""); const user = JSON.parse(localStorage.getItem("procurement_user") || "{}"); setAdmin(Boolean(user.roles?.includes("workspace_admin"))); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); if (!file) return setStatus("Vui lòng chọn file nguồn."); const body = new FormData(); body.append("token", token); body.append("file", file); body.append("title", form.title); body.append("classification", form.classification); body.append("allowed_departments", form.departments); body.append("allowed_roles", form.roles); setStatus("Đang chuyển file vào private storage…"); const response = await fetch(`${API}/admin/documents`, { method: "POST", body }); const data = await response.json(); setStatus(response.ok ? `Đã tạo ${data.document_id}. Hệ thống đang trích xuất và lập chỉ mục.` : data.detail || "Upload thất bại."); }
  return <AppShell><section className="page-heading compact"><div><span className="enterprise-eyebrow">SECURE INGESTION</span><h1>Tải tài liệu</h1><p>Gắn access policy trước khi tài liệu được chia chunk và embedding.</p></div></section>{!admin ? <section className="enterprise-panel permission-gate"><LockKeyhole size={28} /><h2>Bạn chưa có quyền nạp tài liệu</h2><p>Workspace admin quản lý nguồn dữ liệu và access policy cho knowledge base.</p></section> : <section className="upload-layout"><form className="enterprise-panel upload-form" onSubmit={submit}><h2>Thông tin tài liệu</h2><label>Tiêu đề tài liệu<input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} required /></label><label>File nguồn<input type="file" accept=".pdf,.docx,.txt" onChange={(event) => setFile(event.target.files?.[0])} required /></label>{file && <div className="selected-upload"><FileText size={19} /><span>{file.name}</span></div>}<div className="form-columns"><label>Phân loại<select value={form.classification} onChange={(event) => setForm({ ...form, classification: event.target.value })}><option value="internal">Internal</option><option value="confidential">Confidential</option></select></label><label>Phòng ban được phép<input value={form.departments} onChange={(event) => setForm({ ...form, departments: event.target.value })} /></label></div><label>Roles được phép<input value={form.roles} onChange={(event) => setForm({ ...form, roles: event.target.value })} /></label><button className="primary-button">Nạp vào knowledge base</button>{status && <p className="upload-status">{status}</p>}</form><aside className="upload-aside"><div className="enterprise-panel dark-note"><ShieldCheck size={21} /><h3>Secure by design</h3><p>File gốc không công khai. ACL metadata theo tenant, department và role được gắn vào từng chunk trước retrieval.</p></div><div className="enterprise-panel"><h3>Luồng xử lý</h3><ol><li>Private S3 storage</li><li>Text extraction</li><li>Chunking + embedding</li><li>pgvector HNSW index</li></ol></div></aside></section>}</AppShell>;
}
