"use client";

import { Activity, Database, FileLock2, ShieldCheck, UsersRound } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { AppShell } from "../components/app-shell";

export default function GovernancePage() {
  const [admin, setAdmin] = useState(false);
  useEffect(() => { const user = JSON.parse(localStorage.getItem("procurement_user") || "{}"); setAdmin(Boolean(user.roles?.includes("workspace_admin"))); }, []);
  return <AppShell><section className="page-heading compact"><div><span className="enterprise-eyebrow">SECURITY GOVERNANCE</span><h1>Quản trị tri thức</h1><p>Kiểm soát nguồn dữ liệu, access policy và dấu vết truy cập.</p></div></section>{!admin ? <section className="enterprise-panel permission-gate"><ShieldCheck size={28} /><h2>Workspace admin only</h2><p>Tài khoản của bạn không có quyền xem khu vực governance.</p></section> : <><section className="metric-grid governance-metrics"><article className="metric-card"><div className="metric-icon purple"><UsersRound size={20} /></div><span>Identity & roles</span><strong>RBAC</strong><small>Vai trò xác định phạm vi truy cập</small></article><article className="metric-card"><div className="metric-icon green"><FileLock2 size={20} /></div><span>Document ACL</span><strong>ABAC</strong><small>Department + classification metadata</small></article><article className="metric-card"><div className="metric-icon blue"><Database size={20} /></div><span>Vector isolation</span><strong>RLS</strong><small>Tenant context cho PostgreSQL</small></article><article className="metric-card"><div className="metric-icon orange"><Activity size={20} /></div><span>Audit trail</span><strong>ON</strong><small>Query và ingestion events</small></article></section><section className="dashboard-columns"><article className="enterprise-panel governance-list"><div className="panel-heading"><div><span>DATA SOURCES</span><h2>Knowledge ingestion</h2></div><Link href="/upload" className="primary-button">Nạp tài liệu</Link></div><p>Admin quản lý nguồn ở S3 private và đặt ACL trước khi embedding. User portal không hiển thị tài liệu không thuộc quyền truy cập.</p></article><article className="enterprise-panel governance-list"><div className="panel-heading"><div><span>ACCESS CONTROLS</span><h2>Security posture</h2></div><ShieldCheck size={22} /></div><ul><li>Tenant filter bắt buộc trong pgvector query</li><li>Department/role ACL tại từng chunk</li><li>HNSW cosine vector index</li><li>Audit event theo organization</li></ul></article></section></>}</AppShell>;
}
