"use client";

import { ArrowUp, Bot, FileSearch, Quote, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { AppShell } from "../components/app-shell";

const API = process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8080/api";
type Message = { role: "user" | "assistant"; content: string; citations?: { document_id: string; title: string; classification: string; excerpt: string }[] };

export default function AssistantPage() {
  const [token, setToken] = useState(""); const [question, setQuestion] = useState(""); const [messages, setMessages] = useState<Message[]>([]); const [loading, setLoading] = useState(false);
  useEffect(() => setToken(localStorage.getItem("procurement_token") || ""), []);
  async function ask(event?: FormEvent) { event?.preventDefault(); if (!question.trim() || loading) return; const value = question.trim(); setMessages((items) => [...items, { role: "user", content: value }]); setQuestion(""); setLoading(true); const response = await fetch(`${API}/knowledge/ask`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, question: value }) }); const data = await response.json(); setMessages((items) => [...items, { role: "assistant", content: data.answer || data.detail || "Không thể truy xuất lúc này.", citations: data.citations }]); setLoading(false); }
  return <AppShell><div className="assistant-page"><header className="assistant-header"><div><span className="enterprise-eyebrow"><Sparkles size={14} /> TRỢ LÝ RAG NỘI BỘ</span><h1>Hỏi KnowledgeOS</h1><p>Câu trả lời chỉ dựa trên các tài liệu bạn được phép truy cập.</p></div><div className="security-pill"><ShieldCheck size={16} />Secure context only</div></header><section className="chat-surface"><div className="chat-scroll">{!messages.length ? <div className="assistant-welcome"><div className="assistant-symbol"><Bot size={31} /></div><span className="enterprise-eyebrow">SẴN SÀNG TRA CỨU</span><h2>Đặt câu hỏi bằng ngôn ngữ tự nhiên</h2><p>KnowledgeOS lọc quyền trước khi tìm vector và chỉ đưa permitted context vào câu trả lời.</p><div className="suggestion-grid"><button onClick={() => setQuestion("Quy trình phê duyệt mua phần mềm là gì?")}><FileSearch size={19} />Quy trình phê duyệt mua phần mềm</button><button onClick={() => setQuestion("Tóm tắt quy định công tác phí.")}><Quote size={19} />Tóm tắt quy định công tác phí</button><button onClick={() => setQuestion("Tài liệu nào tôi có thể sử dụng?")}><ShieldCheck size={19} />Phạm vi truy cập của tôi</button></div></div> : <div className="message-list">{messages.map((message, index) => <article className={`chat-message ${message.role}`} key={index}><div className="message-avatar">{message.role === "assistant" ? <Bot size={18} /> : <UserRound size={18} />}</div><div><strong>{message.role === "assistant" ? "KnowledgeOS" : "Bạn"}</strong><p>{message.content}</p>{message.citations?.length ? <div className="citation-list"><span>Nguồn tham chiếu được phép</span>{message.citations.map((citation) => <details key={citation.document_id}><summary>{citation.title}<em>{citation.classification}</em></summary><p>{citation.excerpt}</p></details>)}</div> : null}</div></article>)}{loading && <div className="thinking">Đang truy xuất secure knowledge base…</div>}</div>}</div><form className="chat-composer" onSubmit={ask}><textarea value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Hỏi về chính sách, quy trình, hợp đồng…" /><button aria-label="Gửi" disabled={!question.trim() || loading}><ArrowUp size={19} /></button><span>Enter để gửi · Shift + Enter để xuống dòng</span></form></section></div></AppShell>;
}
